CREATE (:Account {id: 'company', name: 'Big Company', createdOn: datetime()})
CREATE (:Account {id: 'bank', name: 'Big Bank', createdOn: datetime()})
CREATE (:Account {id: 'aig', name: 'Insurance Company', createdOn: datetime()})
CREATE (:Account {id: 'bankAccount', name: 'Checkings Account', createdOn: datetime()})
CREATE (:Account {id: 'loans', name: 'Loans', createdOn: datetime()})-[:childOf]->(bnkAcc)
CREATE (:Account {id: 'carloan', name: 'Car loan', createdOn: datetime()})-[:childOf]->(loans)
CREATE (:Account {id: 'renovationsloan', name: 'Renovations loan', createdOn: datetime()})-[:childOf]->(loans)
CREATE (:Account {id: 'mortgages', name: 'Mortgages', createdOn: datetime()})-[:childOf]->(bnkAcc)
CREATE (:Account {id: 'mortgages_home', name: 'Home mortgage', createdOn: datetime()})-[:childOf]->(mrtg)
CREATE (:Account {id: 'mortgages_office', name: 'Office mortgage', createdOn: datetime()})-[:childOf]->(mrtg)
CREATE (:Account {id: 'insurances', name: 'Insurances', createdOn: datetime()})-[:childOf]->(bnkAcc)
CREATE (:Account {id: 'insurances_life', name: 'Life insurance', createdOn: datetime()})-[:childOf]->(insr)
CREATE (:Account {id: 'insurances_health', name: 'Health insurance', createdOn: datetime()})-[:childOf]->(insr)
