CREATE (company:Account {id: 'company', name: 'Big Company', createdOn: datetime()})
CREATE (bank:Account {id: 'bank', name: 'Big Bank', createdOn: datetime()})
CREATE (aig:Account {id: 'aig', name: 'Insurance Company', createdOn: datetime()})
CREATE (bankAccount:Account {id: 'bankAccount', name: 'Checkings Account', createdOn: datetime()})
CREATE (loans:Account {id: 'loans', name: 'Loans', createdOn: datetime()})-[:childOf]->(bankAccount)
CREATE (carLoan:Account {id: 'carLoan', name: 'Car loan', createdOn: datetime()})-[:childOf]->(loans)
CREATE (renovationsLoan:Account {id: 'renovationsLoan', name: 'Renovations loan', createdOn: datetime()})-[:childOf]->(loans)
CREATE (mortgages:Account {id: 'mortgages', name: 'Mortgages', createdOn: datetime()})-[:childOf]->(bankAccount)
CREATE (homeMortgage:Account {id: 'homeMortgage', name: 'Home mortgage', createdOn: datetime()})-[:childOf]->(mortgages)
CREATE (officeMortgage:Account {id: 'officeMortgage', name: 'Office mortgage', createdOn: datetime()})-[:childOf]->(mortgages)
CREATE (insurances:Account {id: 'insurances', name: 'Insurances', createdOn: datetime()})-[:childOf]->(bankAccount)
CREATE (lifeInsurance:Account {id: 'lifeInsurance', name: 'Life insurance', createdOn: datetime()})-[:childOf]->(insurances)
CREATE (healthInsurance:Account {id: 'healthInsurance', name: 'Health insurance', createdOn: datetime()})-[:childOf]->(insurances)
