// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package test

import (
	"github.com/bluebudgetz/gate/internal/app"
	"github.com/bluebudgetz/gate/internal/server"
	"github.com/bluebudgetz/gate/internal/server/handlers"
)

// Injectors from wire.go:

func InitializeApp() (*app.App, func(), error) {
	config, err := NewConfig()
	if err != nil {
		return nil, nil, err
	}
	registry := server.NewPrometheusRegistry()
	driver, cleanup, err := NewNeo4jDriver()
	if err != nil {
		return nil, nil, err
	}
	routes := handlers.NewRoutes(driver)
	mux := server.NewChiRouter(config, registry, routes)
	v := server.NewHTTPServers(config, mux)
	appApp, err := app.NewApp(config, v)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return appApp, func() {
		cleanup()
	}, nil
}
