version: "3"
services:

  gate:
    build:
      context: .
      dockerfile: build/Dockerfile
    restart: on-failure
    depends_on:
      - mongo
    environment:
      BB_LOG_FORMAT: pretty
      BB_DATABASE_MONGODB_HOST: mongo
    ports:
      - 3001:3001

  mongo:
    image: mongo:4.0
    command:
      - --smallfiles
      - --wiredTigerCacheSizeGB=1.5
      - --bind_ip=0.0.0.0
      - --quiet
    environment:
      MONGO_INITDB_DATABASE: bluebudgetz
    volumes:
      - ./init-mongodb.js:/docker-entrypoint-initdb.d/init-bluebudgetz-db.js
    ports:
      - 27017:27017
