name: Build branch
on:
  push:
    branches: ["!master"]
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      neo4j:
        image: docker.pkg.github.com/bluebudgetz/neo4j/neo4j:v0.0.1
        ports: [7473:7473, 7687:7687]
    steps:
      - name: Clone
        uses: actions/checkout@v1
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Test
        run: go test ./...
      - name: Vet
        run: go vet ./...
      - name: Formatting
        run: |
          find . -name assets_gen.go -execdir mv '{}' '.{}' ';'
          test -z "$(gofmt -s -l -d -e . | tee /dev/stderr)"
          git clean -fd && git checkout .
      - name: Docker login
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login docker.pkg.github.com -u arikkfir -p "${GITHUB_TOKEN}"
      - name: Build ref mage
        run: docker build --tag=docker.pkg.github.com/${GITHUB_REPOSITORY}/gate:${GITHUB_SHA::7} .
      - name: Push ref image
        run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/gate:${GITHUB_SHA::7}
