name: CI
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: go test ./...

    - name: Vet
      run: go vet ./...

    - name: Formatting
      run: |
        find . -name assets_gen.go -execdir mv '{}' '.{}' ';'
        test -z "$(gofmt -s -l -d -e . | tee /dev/stderr)"
        git clean -fd && git checkout .

    - name: Docker login
      run: docker login docker.pkg.github.com -u arikkfir -p ${{ secrets.GITHUB_TOKEN }}

    - name: Build Image
      run: docker build --file=build/Dockerfile --tag=docker.pkg.github.com/${GITHUB_REPOSITORY}/${GITHUB_REPOSITORY}:${GITHUB_SHA} .

    - name: Push Image
      run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/${GITHUB_REPOSITORY}:${GITHUB_SHA}
