name: Build release
on:
  release:
    types: [published]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - env:
          DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        run: |
          docker login --username arikkfir -p "${DOCKERHUB_ACCESS_TOKEN}"
          docker pull ${GITHUB_REPOSITORY}:${GITHUB_SHA::7}
          docker tag ${GITHUB_REPOSITORY}:${GITHUB_SHA::7} ${GITHUB_REPOSITORY}:$(cut -d'/' -f3 <<<${GITHUB_REF})
          docker push ${GITHUB_REPOSITORY}:$(cut -d'/' -f3 <<<${GITHUB_REF})
